# Generated by Django 4.2.5 on 2023-10-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/product_images/default.png', upload_to='static/product_images'),
        ),
    ]
