# Generated by Django 4.2.5 on 2023-10-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_details_product_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desciption',
            new_name='description',
        ),
    ]
