# Generated by Django 4.2.5 on 2023-10-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_desciption_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/product_images/default.png', upload_to='meida/product_images'),
        ),
    ]
