# Generated by Django 4.2.5 on 2023-10-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/product_images/default.png', upload_to='product_images'),
        ),
    ]
