# Generated by Django 4.2.5 on 2023-10-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_image_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/products/default.jpg', upload_to='products/'),
        ),
    ]
