# Generated by Django 4.2.5 on 2023-10-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
