# Generated by Django 4.2.5 on 2023-10-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_cartid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='productid',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='userid',
        ),
    ]
