# Generated by Django 4.2.5 on 2023-10-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_product_cart_productid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='userid',
            new_name='user',
        ),
    ]
